#!/usr/bin/env python

import sys,os

def printXML(cliPath):
    xmlFP = open(cliPath + ".xml", "r")
    print(xmlFP.read())
    xmlFP.close()

def main ():
    for path in sys.path:
        if "Slicer" in path and path.endswith("bin"):
            pathSlicerPython = os.path.join(path, "SlicerPython")
    currentPath = os.path.dirname(os.path.abspath(__file__))
    remainingArgs = [pathSlicerPython, os.path.join(currentPath ,"Wrapper","envTensorFlowWrapper.py"), os.path.join(currentPath,"Resources", "Classifier","evalShape.py")]
    for arg in sys.argv[1:]:
        if arg in ("-x", "--xml"):
            printXML(sys.argv[0])
            return
        else:
            remainingArgs.append(arg)

    print remainingArgs
    command = "%s %s -pgm %s -args \"{'%s': '%s'}\"" % tuple(remainingArgs)

    exit(os.system(command))

if __name__ == '__main__':
    try:
        main()
    except Exception, e:
        print ('ERROR, UNEXPECTED EXCEPTION')
        print str(e)
        import traceback
        traceback.print_exc()