repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: "v4.4.0"
  hooks:
  - id: check-ast
  - id: check-added-large-files
    args: ['--maxkb=1024']
  - id: check-case-conflict
  - id: check-merge-conflict

- repo: https://github.com/asottile/pyupgrade
  rev: v3.3.0
  hooks:
  -   id: pyupgrade
      args: [--py39-plus]
